name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7
      - name: Build project
        run: ./gradlew clean build
        env:
          TAG_VERSION: ${{ github.ref }}
      - run: |
          assetsAAR=$(find . -name *release.aar | while read -r asset ; do echo "-a $asset" ; done)
          VERSION=$(echo $TAG_VERSION | cut -d'/' -f3)
          assetsJAR=$(find . -name IOIO*${VERSION}.jar | while read -r asset ; do echo "-a $asset" ; done)
          tag_name="${GITHUB_REF##*/}"
          hub release create ${assetsAAR} ${assetsJAR} -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_VERSION: ${{ github.ref }}
